
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.eframe]
audit-as-crates-io = false

[policy.egui-winit]
audit-as-crates-io = false

[[exemptions.quinn]]
version = "0.11.11"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.17"
criteria = "safe-to-deploy"

[[exemptions.quinn-udp]]
version = "0.5.15"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.rand_pcg]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.rcgen]]
version = "0.13.2"
criteria = "safe-to-run"

[[exemptions.rusticata-macros]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.x509-parser]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.yasna]]
version = "0.5.2"
criteria = "safe-to-run"
